const initialState = {
  products: {
    data: [
      {
        id: '1',
        name: 'Creme bag',
        minPrice: 3,
        image: '/images/products/creme/creme1.jpeg',
        mainColor: '#F5DBCB',
        description: 'A beautiful design created by John Doe. We are honored to show you our 100% eco tote bags. We allocate 10% of our profits to climate-change fighting organizations.',
        photos: [
          '/images/products/creme/creme1.jpeg',
          '/images/products/creme/creme2.jpeg',
          '/images/products/creme/creme3.jpeg',
          '/images/products/creme/creme4.jpeg',
        ],
      },
      {
        id: '2',
        name: 'Pink bag',
        minPrice: 5,
        image: '/images/products/pink/pink1.jpeg',
        mainColor: '#e9d3d6',
        description: 'A beautiful design created by Amanda Doe. We are honored to show you our 100% eco tote bags. We allocate 10% of our profits to climate-change fighting organizations.',
        photos: [
          '/images/products/pink/pink1.jpeg',
          '/images/products/pink/pink2.jpeg',
          '/images/products/pink/pink3.jpeg',
          '/images/products/pink/pink4.jpeg',
        ],
      },
      {
        id: '3',
        name: 'Eco white',
        minPrice: 7,
        image: '/images/products/white/white1.jpg',
        mainColor: '#31572c',
        description: 'A beautiful design created by John Doe. We are honored to show you our 100% eco tote bags. We allocate 10% of our profits to climate-change fighting organizations.',
        photos: [
          '/images/products/white/white1.jpg',
          '/images/products/white/white2.jpg',
          '/images/products/white/white3.jpg',
          '/images/products/white/white4.jpg',
        ],
      },
      {
        id: '4',
        name: 'Andy Warhol',
        minPrice: 9,
        image: '/images/products/warhol/warhol1.png',
        mainColor: '#fb8500',
        description: 'A beautiful design created by Amanda Doe. Inspired by Andy Warhol works. We allocate 10% of our profits to climate-change fighting organizations.',
        photos: [
          '/images/products/warhol/warhol1.png',
          '/images/products/warhol/warhol2.png',
          '/images/products/warhol/warhol3.png',
          '/images/products/warhol/warhol4.png',
        ],
      },
      {
        id: '5',
        name: 'Gustav Klimt',
        minPrice: 11,
        image: '/images/products/klimt/klimt1.png',
        mainColor: '#7d8597',
        description: 'A beautiful design created by John Doe. Inspired by Gustav Klimt works. We allocate 10% of our profits to climate-change fighting organizations.',
        photos: [
          '/images/products/klimt/klimt1.png',
          '/images/products/klimt/klimt2.png',
          '/images/products/klimt/klimt3.png',
          '/images/products/klimt/klimt4.png',
        ],
      },
      {
        id: '6',
        name: 'Claude Monet',
        minPrice: 13,
        image: '/images/products/monet/monet1.png',
        mainColor: '#862906',
        description: 'A beautiful design created by Amanda Doe. Inspired by Claude Monet works. We allocate 10% of our profits to climate-change fighting organizations.',
        photos: [
          '/images/products/monet/monet1.png',
          '/images/products/monet/monet2.png',
          '/images/products/monet/monet3.png',
          '/images/products/monet/monet4.png',
        ],
      },
      {
        id: '7',
        name: 'Pablo Picasso',
        minPrice: 15,
        image: '/images/products/picasso/picasso1.png',
        mainColor: '#fdeed9',
        description: 'A beautiful design created by John Doe. Inspired by Pablo Picasso works. We allocate 10% of our profits to climate-change fighting organizations.',
        photos: [
          '/images/products/picasso/picasso1.png',
          '/images/products/picasso/picasso2.png',
          '/images/products/picasso/picasso3.png',
          '/images/products/picasso/picasso4.png',
        ],
      },
      {
        id: '8',
        name: 'Violet smile',
        minPrice: 17,
        image: '/images/products/violet-smile/smile1.png',
        mainColor: '#6200b3',
        description: 'A beautiful design created by Amanda Doe. We are honored to show you our 100% eco tote bags. We allocate 10% of our profits to climate-change fighting organizations.',
        photos: [
          '/images/products/violet-smile/smile1.png',
          '/images/products/violet-smile/smile2.png',
          '/images/products/violet-smile/smile3.png',
          '/images/products/violet-smile/smile4.png',
        ],
      },
    ],
  },
  cart: [],
  orders: [],
};

export default initialState;
